FROM python:3.11-slim

WORKDIR /app

# system deps (optional but useful)
RUN pip install --no-cache-dir -U pip

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY src /app/src

CMD ["python", "-m", "src.ingestion.binance"]
